<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon birth-doc"></div>
                    <div class="heading-text">
                        <h2>Birth Documents</h2>
                        <h3>Government is a choice, not an obligation</h3>
                    </div>
                </div>
                <p>
                    Parents of a new born are free to record their offspring with the RGH. You are required to provide proof of birth,
                    such as an affidavit from a medical practitioner and a relevant witness as well as your babies footprint,
                    and details. You will find the required documents in your account pages.
                </p>
                <p>
                    Once the documents have been uploaded to our system and checked by one of our volunteers, a name and
                    identity number will be issued which forms the basis of your babies legal identity.
                </p>
                <p>
                    There is no charge for the service and no guarantees that world government agencies will recognise the
                    documents. The validity of any document issued by the RGH is self evident, however it is up to you to
                    protect your human rights when claiming the validity of a document.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>