<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon birth-doc"></div>
                    <div class="heading-text">
                        <h2>Birth Documents</h2>
                        <h3>Government is a choice, not an obligation</h3>
                    </div>
                </div>
                <p>
                    Parents of new borns are free to record their offspring with the RGH. It is a matter of entering in the
                    required information, attesting to its validity and printing out the associated documents.
                </p>
                <p>
                    There is no charge for the service and no guarantees that world government agencies will recognise the
                    documents. The validity of any document issued by the RGH is self evident, however it is up to you to
                    protect your human rights when claiming the validity of a document.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>