<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon company-reg"></div>
                    <div class="heading-text">
                        <h2>Company Registrations</h2>
                        <h3>Setup a company / trust.</h3>
                    </div>
                </div>
                <p>
                    We offer a facility where you can create an RGH based corporation or trust as well as other legal persons
                    that you may require in your day to day activities.
                </p>
                <p>
                    All details are listed via our chamber of commerce.
                </p>
                <p>
                    There is no charge for basic corporation creation. If you require filing with local attorneys, this is a
                    cost between you and your chosen representatives.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>