<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon company-reg"></div>
                    <div class="heading-text">
                        <h2>Company Registrations</h2>
                        <h3>Setup a company / trust.</h3>
                    </div>
                </div>
                <p>
                    Soon you will be able to record companies and trusts within the scope of the
                    republic. Our service witnesses and records your intention and provides a unique
                    identity for your private use.
                </p>
                <p>
                    All details will be listed via our "chamber of commerce" for lack of a better description.
                </p>
                <p>
                    There will be no charge for this service, we simply bare witness to the persona you choose to create and
                    provide a downloadable certificate for your use.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>