<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon licensing"></div>
                    <div class="heading-text">
                        <h2>Conveyance records</h2>
                        <h3>Recording your property with the <em>republic</em></h3>
                    </div>
                </div>
                <p>
                    You are free to record any conveyance in your possession with the <em>republic</em>. This is a
                    unique and private record of your property and serves as a private jurisdiction under your command.
                    As with all services designed by the citizens of the republic, and our commitment to build a society
                    outside the realms of debt currency, there is no charge.
                </p>
                <p>
                    Should you choose to travel the international highways and byways with your <em>republic</em> recorded property
                    you do so freely and at your own risk. In addition you commit to ensuring that you conduct yourself in a manner
                    that preserves the safety of all people and understand that you are responsible at all times for your actions.
                </p>
                <p>
                    If it is your intention to terminate a contractual relationship with a third party registrar,
                    it would be advisable to put your intentions in writing and inform the third party accordingly.
                    In some cases it would be advisable to use the local courts, to whom a registrar is bound, in order
                    to keep a record of your intentions. This may be useful in the event a contractual relationship is questioned.
                </p>
                <p>

                    The <em>republic</em> will not get involved in disputes
                    other than to confirm or deny a record in the system as may be requested from time to time.
                </p>
                <p>
                    Be advised that currently this service is managed by volunteers.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>