<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon licensing"></div>
                    <div class="heading-text">
                        <h2>Conveyance records</h2>
                        <h3>Recording your property with the RGH</h3>
                    </div>
                </div>
                <p>
                    A fundamental freedom of a people is the freedom of movement. With this in mind
                    you are welcome to record your choice of conveyance with the society in order to express your rights to the
                    freedom of movement.
                </p>
                <p>
                    Do note that for people w
                </p>
                <p>
                    There is no charge for this service.
                </p>
                <p>
                    Traveling under the banner of the RGH is strictly for human rights activists who are versed with local
                    law and legislation and who have a legal network to backup their rights and claims.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>