<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon identity"></div>
                    <div class="heading-text">
                        <h2>Frequently asked questions</h2>
                        <h3>We attempt to ask common questions asked by interested parties</h3>
                    </div>
                </div>
                <p>
                    NOTICE: These answers are general answers and offered without prejudice.
                </p>
                <h2>WHO RUNS THE REPUBLIC?</h2>
                <p>
                    The republic is a set of community based tools provided and
                    built by its members. We have administrators who offer their time and energy with the intention of
                    networking our members with each other in order to create new and better services. The republic was
                    formed shortly after a declaration of independence and enjoys a global member base.
                </p>
                <h2>WHAT IS THE REPUBLICS CONSTITUTION?</h2>
                <p>
                    This is a common question and our members have been on the look out for a barely used one.
                    As it stands, we have found a very good constitution, with one previous owner, that requires some small adjustments
                    before it will be made available for comment.
                </p>
                <h2>WHAT IS THE VISION OF THE REPUBLIC?</h2>
                <p>
                    We believe there is a better way to manage society other than through the use of debt financial systems.
                    We can not claim to have a solution, however, it is what we are striving towards.
                </p>

                <h2>WHAT IS THE PURPOSE OF THE REPUBLIC?</h2>
                <p>
                    The idea behind the republic is to provide a vehicle for a people to use in order to take a stand
                    against debt monetary systems. We are pro-a-good-and-sensible-republic managing a society based on
                    equality, and a big part of this is to ensure that the energy system we choose to use (our means of exchange)
                    empowers and uplifts all people.
                </p>
                <p>
                    In a sentence: we are creating a world without debt.
                </p>
                <h2>WHERE IS THE REPUBLIC LOCATED ON A MAP?</h2>
                <p>
                    The republic is an <em>artificial person</em> (like all nations and governments), there is nothing to visit, no geography to
                    point out and certainly no ground to walk upon. It is not possible to stand in the legal substance of any country
                    as a "people", in order to enter a countries substance (jurisdiction) you must act as its citizen (a <em>persona</em>).
                </p>
                <p>
                    If you take the time to read various nations statute and acts,
                    you will notice that when it comes to defining the borders of a nation, legally speaking, it is more often
                    than not, vague and contradictory. Essentially a nation exercises jurisdiction by consent, and in the absence of
                    consent, it has no jurisdiction (think contractual relationship).
                </p>
                <h2>WHAT IS THE DIFFERENCE BETWEEN THE REPUBLIC AND A TRADITIONAL STATE?</h2>
                <p>
                    The republic is 100% voluntary and 100% debt free. Our aim is to provide services using private
                    capital (debt and interest free energy) in order to build the things we need without burdening
                    the people. And if you don't ike the way it all works, you
                    are free to leave. And leaving simply means, no longer using its services and identifying
                    with its brand.
                </p>
                <p>
                    A traditional state on the other hand, imposes and inserts itself between you and the people you wish to
                    interact with. You could look at a traditional Citizen as a type of tax cattle for a government that
                    serves as an interface between the purveyors of interest (parasites who make their money through usurious
                    means) and you. As an example, a state that borrows excessively to produce things that the citizenry don’t
                    want or have no need for but due to their status as tax cattle have little choice other than wasting their energy
                    on never ending taxes used to pay the interest on fictitious debts.
                </p>
                <h2>HOW DO I REGISTER MY CAR WITH THE REPUBLIC?</h2>
                <p>
                    The republic does not "register" anything in the public, services are limited to a "record" of private property and the
                    verification of that record should the need arise. How you choose to use your record is up to you and you take full responsibility
                    for your actions and any consequences that may arise from them.
                </p>
                <h2>CAN I GET MARRIED IN THE REPUBLIC?</h2>
                <p>
                    The republic is more than happy to record a union between two people. However, you may wish to carefully consider
                    your options before deciding a course of action.
                </p>
                <h2>HOW DO I RECORD MY NEW BORN'S BIRTH?</h2>
                <p>
                    Before a <em>persona</em> can be "recorded", you will need to provide proof of birth which should
                    be signed by at least two medical practitioners (witnesses). In addition to this, you will need to provide the
                    name that you gift to your new born (affidavit). Once this has been received, you will have the opportunity to
                    create an express trust, the asset of which is the title to the new born's name. From this you are issued with
                    a birth certificate which reflects our record of the full legal persona or citizen.
                </p>
                <p>
                    Please note that the birth record we offer is a private record. It does not replace a record you may wish to use
                    with a traditional nation state. While we believe registering a birth in the traditional sense offers your new born's energy
                    as collateral to current and future debts, it is up to you to make an informed decision as to what you wish to do.
                </p>
                <h2>HOW DO I OBTAIN AN ID DOCUMENT AND PASSPORT?</h2>
                <p>
                    In order to obtain a passport and ID document, you must go through a similar process to that of a new born.
                    You will need to provide affidavits of your given name and your claim to its title. Once received
                    you will have an opportunity to create an express trust with title of the name as an asset of trust.
                </p>
                <p>
                    Once you have completed the process, the private documentation will be made available to your account pages.
                </p>
                <h2>CAN I OBTAIN A DRIVERS LICENSE?</h2>
                <p>
                    No.
                </p>
            </div>
            <div class="col-sm-4 col-md-3">
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/logo1.jpg" >
                    </div>
                    <div class="text">
                        <p>Citizens of the Republic of Good Hope are human rights activists focusing on violations against humanity by incorporated State and various organs of State.</p>
                        <p>Our goal is to protect minority  groups with specifics to the following rights:</p>
                        <ol>
                            <li>Freedom of movement</li>
                            <li>Freedom of Association</li>
                            <li>Freedom from Slavery</li>
                        </ol>
                        <p>We focus on slavery through finance and the knock on effect this has on the people of this earth.</p>
                        <p>Our method is to neutralise human rights violations through tribunals, public listings of offenders and the
                            reporting of violations to the UN High Commission.</p>
                        <p>We are a privately funded  organization.</p>
                    </div>
                </div>
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/logo2.jpg" >
                    </div>
                    <div class="text">
                        <p>A cornerstone of the Republic of Good Hope is the Universal Declaration of Human Rights declared in Paris in 1948.</p>
                        <p>We encourage your to read this document and to take the time to learn your rights. It is by knowing your rights that we can create a better world together.</p>
                        <p><a href="http://www.un.org/en/universal-declaration-human-rights/">http://www.un.org/en/universal-
                                declaration-human-rights/</a></p>
                    </div>
                </div>


            </div>

        </div>



    </div>
</div>