<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon identity"></div>
                    <div class="heading-text">
                        <h2>Identity</h2>
                        <h3>Protecing your right to the "Security of the person"</h3>
                    </div>
                </div>
                <p>Understanding that the security of the person refers to the security of the legal substance that a people may freely choose to bind themselves to is not only a fundamental human right it is also a basic contractual relationship between the various parties.</p>
                <p>We believe that a people have a fundamental right to choose who they identify and contract with and by using an RGH identity document you are freely choosing to contract and identify with the Republic of Good Hope.</p>
                <p>The purpose of using the RGH Identity is to show third parties that you are exercising a right. Anyone who attempts to violate this right will be summoned to a human rights tribunal.</p>

                <h2>HOW IT WORKS</h2>
                <p>Our identity documents are based on the RGH Birth Certificate which is derived from a notice of live birth. Should a notice of live birth not be available an affidavit by a competent authority will suffice.</p>
                <h2>THIRD PARTY OFFICIALS DEALING WITH OFFENSES BY RGH IDENTIFIED CITIZENS</h2>
                <p>RGH Citizens are not immune from prosecution. By oath they are compelled to obey local custom and adhere to their community standards. Officials dealing with RGH citizens are encouraged to understand the fundamentals of human rights and why they need to treat RGH citizens with due caution since it is easy to violate human rights and become the subject of a human rights investigation.</p>
                <p>It is important to understand that RGH Citizens do not engage with debt monetary systems and to demand any form of payment in this reard will lead to a human rights investigation.</p>
                <p>Remedy in terms of community service will be accepted in lieu of debt payment for any violation of a local custom.</p>

            </div>
            <div class="col-sm-4 col-md-3">
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/logo1.jpg" >
                    </div>
                    <div class="text">
                        <p>Citizens of the Republic of Good Hope are human rights activists focusing on violations against humanity by incorporated State and various organs of State.</p>
                        <p>Our goal is to protect minority  groups with specifics to the following rights:</p>
                        <ol>
                            <li>Freedom of movement</li>
                            <li>Freedom of Association</li>
                            <li>Freedom from Slavery</li>
                        </ol>
                        <p>We focus on slavery through finance and the knock on effect this has on the people of this earth.</p>
                        <p>Our method is to neutralise human rights violations through tribunals, public listings of offenders and the
                            reporting of violations to the UN High Commission.</p>
                        <p>We are a privately funded  organization.</p>
                    </div>
                </div>
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/logo2.jpg" >
                    </div>
                    <div class="text">
                        <p>A cornerstone of the Republic of Good Hope is the Universal Declaration of Human Rights declared in Paris in 1948.</p>
                        <p>We encourage your to read this document and to take the time to learn your rights. It is by knowing your rights that we can create a better world together.</p>
                        <p><a href="http://www.un.org/en/universal-declaration-human-rights/">http://www.un.org/en/universal-
                                declaration-human-rights/</a></p>
                    </div>
                </div>


            </div>

        </div>



    </div>
</div>