<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon identity"></div>
                    <div class="heading-text">
                        <h2>Frequently asked questions</h2>
                        <h3>We attempt to answer common questions asked by interested parties</h3>
                    </div>
                </div>
                <p>
                    NOTICE: These answers are general answers and offered without prejudice.
                </p>
                <h2>WHO RUNS THE REPUBLIC?</h2>
                <p>
                    The society was created as a result of a declaration of independence and as a vehicle through which a
                    people may record and administer their private affairs without using debt currency. It has a sole
                    responsibility to administer the private affairs of its members. The administration is managed by
                    volunteers who are limited by its constitution.
                </p>
                <h2>WHAT IS THE REPUBLICS CONSTITUTION?</h2>
                <p>
                    The societies constitution outlines the responsibilities of the administrators and the limitations of
                    their mandate.
                </p>
                <p>
                    Each community that wishes to use the tools of the society have a responsibility to draw up their own
                    constitution. It is recommended that you look at the United States constitution, the Canadian constitution
                    or the South African constitution for inspiration.
                </p>
                <h2>WHAT IS THE VISION OF THE REPUBLIC?</h2>
                <p>
                    To empower the world, create work for all people, by removing the scourge of debt monetary systems.
                </p>
                <h2>WHAT IS THE PURPOSE OF THE REPUBLIC?</h2>
                <p>
                    The society is an opportunity for all people to share their energy in order to create better tools to
                    manage the needs of humanity in a post debt currency world.
                </p>
                <h2>WHO IS THE REPUBLIC DESIGNED FOR?</h2>
                <p>
                    Our primary goal is to provide services to people who are prejudiced by debt systems.
                </p>
                <h2>WHERE IS THE REPUBLIC LOCATED ON A MAP?</h2>
                <p>
                    The society is an <em>artificial person</em>, there is nothing to visit, no geography to
                    point out and certainly no ground to walk upon. It is not possible to stand in the legal substance of any country
                    as a "people", in order to enter a countries substance (jurisdiction) you must act as its citizen or equivalent <em>persona</em>.
                </p>
                <p>
                    If you take the time to read various nations statute and acts,
                    you will notice that when it comes to defining the borders of a nation, legally speaking, it is more often
                    than not, vague and contradictory. Essentially a nation exercises jurisdiction by consent, and in the absence of
                    consent, it has no business directing a people.
                </p>
                <h2>WHAT IS THE DIFFERENCE BETWEEN THE REPUBLIC AND A TRADITIONAL STATE?</h2>
                <p>
                    The society is 100% voluntary and 100% debt free. You will not be asked to pay for anything and
                    services are designed in a manner that empowers each member of our society. You
                    are free to leave at any time.
                </p>
                <p>
                    A traditional state on the other hand, imposes and inserts itself between you and the people you wish to
                    interact with. You could look at a traditional Citizen as a type of <em>tax cattle</em> for a government that
                    serves as an interface between the purveyors of interest (parasites who make their money through usurious
                    means) and you, a body of energy that feeds the parasites. As an example, a state that borrows excessively
                    to produce things that the citizenry don’t
                    want or have no need for but due to their status as "tax cattle" have little choice other than to waste their energy
                    on never ending taxes used to pay the interest for the things they did not want in the first place.
                </p>
                <h2>WHAT SERVICES DO YOU OFFER?</h2>
                <p>
                    Our primary goal is to provide free identity and a physical address to people dispossessed as a result of world
                    usury systems. We do this using open source technology, created or managed by our members.
                </p>
                <p>
                    We also strive to offer traditional services most of which require a record. This may be anything from 
                    physical to intellectual property, trusts, wills, etc. Anything a people may require in order to 
                    mange their affairs with dignity.
                </p>
                <h2>CAN I REGISTER MY CAR WITH THE REPUBLIC?</h2>
                <p>
                    The society has designed a process so that you may record any type of conveyance, for free. Do be aware that nations may
                    prejudice you for holding a record with the society and it is best that you are aware of the consequences should you not
                    understand your full body of rights. If you are incapable of protecting your rights, which requires due diligence,
                    it is best that you do not record your conveyance with the society.
                </p>
                <h2>CAN I GET MARRIED IN THE REPUBLIC?</h2>
                <p>
                    The society has designed a process so that you may record your union.
                </p>
                <h2>HOW DO I RECORD MY NEW BORN'S BIRTH?</h2>
                <p>
                    The society has designed a process so that you may record the nativity of your offspring.
                </p>
                <h2>HOW DO I OBTAIN AN ID DOCUMENT AND PASSPORT?</h2>
                <p>
                    The society has designed a process so that you may record a person within the scope of the society.
                </p>
                <h2>CAN I OBTAIN A DRIVERS LICENSE, VISA, WORK PERMIT, RESIDENCY?</h2>
                <p>
                    No. We provide a "record" service only, should you already have these rights, you are welcome to record them with the society.
                </p>
                <h2>HOW DO I GET LEGAL HELP IF I NEED ASSISTANCE?</h2>
                <p>
                    The society does not provide legal assistance nor will it give advice in terms of how the given tools should be used.
                    Each member is responsible for their own actions and seeking the necessary legal advice before using any service offered.
                </p>
                <h2>WHO ARE THE PERPETRATORS OF HUMAN RIGHTS VIOLATIONS?</h2>
                <p>
                    Generally speaking it is vulnerable people who will seek out our services and more often than not, these people are subjected
                    to human rights violations by state officials. It is through these people that we are made aware of
                    human rights violations.
                </p>
                <H2>WHO ARE YOU FUNDED BY?</H2>
                <p>
                    At present we are funded privately however we are seeking investment from various bodies in order to establish a network
                    that will enable us to have a legal team based in every geographical location.
                </p>
                <H2>WHO RECOGNISES YOU?</H2>
                <p>
                    We are recognised by the people who use our services, it is only a matter of time before we are
                    recognised by international bodies.
                </p>
            </div>
            <div class="col-sm-4 col-md-3">
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/logo1.jpg" >
                    </div>
                    <div class="text">
                        <p>Citizens of the Republic of Good Hope are human rights activists focusing on violations against humanity by incorporated State and various organs of State.</p>
                        <p>Our goal is to protect minority  groups with specifics to the following rights:</p>
                        <ol>
                            <li>Freedom of movement</li>
                            <li>Freedom of Association</li>
                            <li>Freedom from Slavery</li>
                        </ol>
                        <p>We focus on slavery through finance and the knock on effect this has on the people of this earth.</p>
                        <p>Our method is to neutralise human rights violations through tribunals, public listings of offenders and the
                            reporting of violations to the UN High Commission.</p>
                        <p>We are a privately funded  organization.</p>
                    </div>
                </div>
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/logo2.jpg" >
                    </div>
                    <div class="text">
                        <p>A cornerstone of the Republic of Good Hope is the Universal Declaration of Human Rights declared in Paris in 1948.</p>
                        <p>We encourage your to read this document and to take the time to learn your rights. It is by knowing your rights that we can create
                            a better world together.</p>
                        <p><a href="http://www.un.org/en/universal-declaration-human-rights/">http://www.un.org/en/universal-declaration-human-rights/</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>