<?php
    $this->layout()->setVariable('include_banner', true);
?>
<div class="page-content">
    <div class="container">
        <h2>What you need to know</h2>
        <p>
            The Republic of Good Hope was declared on the 24 December 2010 as a debt free, moneyless Republic. The purpose of the Republic is to
            encourage a more enlightened form of governance through the use of technology and to develop tools that will assist and empower the
            people in order to take a stand for fundamental human rights.<br/><br/>

            As a Citizen of the Republic, you are tasked with the role of human rights activist. Our aim is to provide our members with
            the necessary tools in order for you to exercise certain rights and to report violations of your rights to various international bodies.<br/><br/>

            Our members determine which rights they wish to stand up for, at present we champion:

        </p>
        <div class="row">
            <div class="col-sm-4">
                <div class="points">
                    <span>1</span>
                    <p>Freedom from Slavery</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="points">
                    <span>2</span>
                    <p>Freedom of Association</p>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="points">
                    <span>3</span>
                    <p>Freedom of Movement</p>
                </div>
            </div>
        </div>
        <p>
            We believe that world governments are complicit in enslaving humanity through debt monetary systems.
            We believe that no charter, constitution or agreement of any kind condones slavery in any form and
            therefore we believe that any government that requires you to pay for anything with a fiat or a debt based
            currency in order for you to exercise your
            fundamental rights are acting in contempt to the spirit of humanity and form part of the problem in this world today.
        </p>
        <p>
            Based on the above premise, we are building services that remove the necessity for a people to use a debt currency
            system in order for them to exercise their fundamental rights.
        </p>
        <div class="row">
            <div class="col-md-4">
                <div class="human-rights-section">
                    <div class="hr-logo">
                        <img src="assets/global/images/human-rights-logo.png" >
                    </div>
                    <p>The Republic of Good Hope has chosen to report Human Rights violators to the UN Office of the high commission. </p>
                    <p> As part of our mandate, we provide our citizens with the tools to exercise and maintain fundamental human rights.</p>
                    <p>
                        Any organisation interfering with a peoples rights are publicly listed in our database and reported to the high commission
                        or a local equivalent.
                    </p>
                </div>
            </div>
            <div class="col-md-8">
                <div class="human-rights-section">
                    <div class="container">
                        <h2>Latest human rights violators</h2>
                        <p>The following lists Governments, Corporations, and individuals who have violated the freedoms of a people.</p>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Geography</th>
                                <th>right violated</th>
                                <th>By whom</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>


                            </tbody>
                        </table>
                        <p>Nothing to report</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="services">
            <h2>Services</h2>
            <p>
                The following services are provided by our society:
            </p>
            <div class="row">
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon identity"></div>
                        <h3>IDENTITY <span>RGH ID DOCUMENT</span> </h3>
                        <p>The RGH offers a common law identity document.</p>
                        <a href="<?=$this->url('identity');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon passport"></div>
                        <h3>PASSPORT <span>TRAVEL DOCUMENT</span> </h3>
                        <p>The RGH offers a passport styled travel document to its members.</p>
                        <a href="<?=$this->url('passport');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon birth-doc"></div>
                        <h3>BIRTH DOCUMENT <span>RECORD OF BIRTH</span> </h3>
                        <p>RGH Birth records and certificates available.</p>
                        <a href="<?=$this->url('birth');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon marriage-doc"></div>
                        <h3>MARRIAGE DOCUMENTS <span>RECORD YOUR UNION</span> </h3>
                        <p>Unions may be recorded via the RGH and related documents are provided.</p>
                        <a href="<?=$this->url('marriage');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon company-reg"></div>
                        <h3>COMPANY REGISTRAR <span>A LEGAL STRUCTURE</span> </h3>
                        <p>Easy to create and manage.</p>
                        <a href="<?=$this->url('company');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon money"></div>
                        <h3>ALTERNATIVE MONEY <span>DEBT & INTEREST FREE</span> </h3>
                        <p>Decentralised money systems free from third party control</p>
                        <a href="<?=$this->url('money');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon licensing"></div>
                        <h3>CONVEYANCE <span>AUTOMOBILE RECORDS</span> </h3>
                        <p>Members are free to record their private conveyance with the society.</p>
                        <a href="<?=$this->url('conveyance');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
                <div class="col-sm-6 col-md-3">
                    <div class="service-box">
                        <div class="icon report"></div>
                        <h3>REPORTING TOOLS <span>REPORT VIOLATORS </span> </h3>
                        <p>We provide tools and processes for you to report Human Rights violators.</p>
                        <a href="<?=$this->url('reporting');?>" class="btn btn-warning">Read more</a>
                    </div>
                </div>
            </div>
            <p>
                Note, all services are provided as is and without warranties.
            </p>
        </div>
        <div class="why-rgh">
            <h2>WHY JOIN THE REPUBLIC OF GOOD HOPE?</h2>
            <p>By becoming an RGH citizen you become a global activist for human rights.</p>
            <ul>
                <li>
                    Guided by the <a href="http://www.un.org/en/universal-declaration-human-rights/" target="_blank">United Nations Universal Declaration of Human Rights</a>
                    your primary role is to report violators to our community. Repeat offenders are reported
                    to the UN offices of the High Commission for human rights (OHCHR).</li>
                <li>
                    Our record keeping process allows us to pin point habitual offenders and to take legal action.
                </li>
                <li>
                    Members of the <a href="http://www.ohchr.org/EN/HRBodies/HRC/Pages/CurrentMembers.aspx" target="_blank">human rights council</a>
                    are accountable and answerable to any human rights violations reported to the OHCR.
                </li>
                <li>
                    Remeber this: <em>The law does not serve to protec those that slumber on their rights.</em> You are responsible for holding fast to what you know to be right.
                </li>
            </ul>
        </div>
        <div class="join-us">
            <p><strong>Join us today in order to build a better tomorrow.</strong></p>
            <button class="btn btn-warning text-uppercase">JOIN NOW</button>
        </div>
    </div>
</div>