<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon identity"></div>
                    <div class="heading-text">
                        <h2>Identity</h2>
                        <h3>Protecting your right to the "Security of the person"</h3>
                    </div>
                </div>
                <p>
                    Security of the person is a basic entitlement guaranteed by the Universal Declaration of Human Rights and adopted by the United Nations in 1948.
                    It is also a human right explicitly mentioned and protected by the Constitution of Canada, the Constitution of South Africa and other laws
                    around the world.
                </p>
                <p>
                    In general, the right to the security of ones person is associated with liberty and includes the right, if one is imprisoned unlawfully,
                    to the remedy of habeas corpus. Security of the person can also be seen as an expansion of rights based on prohibitions of torture and cruel
                    and unusual punishment. Rights to security of person can guard against less lethal conduct, and can be used in regard to prisoners'
                    rights.
                </p>
                <p>
                    You have the right to identify with the RGH and no one by law may subjugate these rights from you.
                </p>

                <h2>VIOLATORS OF THIS RIGHT</h2>

                <p>
                    The right to security of the person is guaranteed by Article 3 of the Universal Declaration of Human Rights. In this article,
                    it is combined with the right to life and liberty. In full, the article reads, "Everyone has the right to life, liberty and
                    security of person."
                </p>
                <p>
                    The United Nations treaty, the International Covenant on Civil and Political Rights (1966), also recognizes a right to
                    security of person. Article 9 states that "Everyone has the right to liberty and security of person," and the section
                    prohibits "arbitrary arrest or detention." The section continues, "No one shall be deprived of his liberty except
                    on such grounds and in accordance with such procedure as are established by law."
                </p>
                <p>
                    <b>Important:</b> You may not be arrested simply by identifying with the RGH. Anyone who arbitrarily arrests a member in this regard
                    will be in violation of article 3 and subjected to a human rights investigation and possible prosecution.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>