<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon marriage-doc"></div>
                    <div class="heading-text">
                        <h2>Marriage Documents</h2>
                        <h3>Your union is private, you have no obligation to marry a government.</h3>
                    </div>
                </div>
                <p>
                    Before the 16th Century, marriage was a private agreement between families, and usually sanctioned by the church.
                    In Colonial America, marriage licenses were issued to prevent bigamy and to legitimize children. As America developed,
                    the government began using marriage licenses as a way to control what races could marry. In her New York Times article
                    “Taking Marriage Private,” Stephanie Coontz reports that “by the 1920s, 38 states prohibited whites from marrying blacks,
                    'mulattos,' Japanese, Chinese, Indians, 'Mongolians,' 'Malays' or Filipinos.” Some states would not issue a license if
                    the bride or groom was considered an addict, a drunk, mentally deficient or previously married. However, by the mid- to
                    late- 20th century, these laws were repealed. Today, licenses are primarily for legal and contractual—not
                    prohibitive—purposes.
                </p>
                <p>
                    There is no charge for the recording of your union. The validity of any document issued by the RGH is self evident,
                    however it is up to you and your partner to formalise your contractual agreements with each other and in a manner that
                    you and your offspring are adequately and legally protected.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>