<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon money"></div>
                    <div class="heading-text">
                        <h2>Alternative money</h2>
                        <h3>Interest and debt free community money</h3>
                    </div>
                </div>
                <p>
                    A vital part of any society is an accepted means of exchange. For the past 100 years fiat currency has been used and it can
                    be argued that the use of this debt money has fueled economic growth and at the same time served to shackle and enslave
                    the worlds people. It was not always like this and history is littered with examples of successful debt-free societies that prospered.
                </p>
                <p>
                    We as a people have a moral objection to using fiat currency in that it can be argued that the control of a countries
                    debt is the control of a countries people.
                </p>
                <p>
                    More and more "traditional" countries from around the world are spending more
                    and more of their taxable income (think peoples energy) on the servicing of debt as apposed to the building of
                    capital infrastructure (schools, hospitals, housing, roads). By accepting external currency as a means of exchange
                    a country essentially gives up its sovereignty. What is interesting is that any sovereign state can produce a
                    private and internal credit system that would better serve the people however it is likely that most world governments
                    are held to ransom as such a proposal would likely inspire financial institutions to crash local housing markets
                    (which is a source of a countries liquidity and an indication of a countries health) which would further cause
                    a variety of rating downgrades which would further collapse an economy.
                </p>
                <p>
                    As it stands, the goal of most societies is to grow an economy by a predefined percentage per year which is not
                    sustainable. A more sustainable model would be to focus on the fundamental needs of all people and build a society that
                    is governed by common sense, as apposed to being directed by interest re-payments created through debt system.
                </p>
                <p>
                    One of the founding principles of our republic is the desire to create the tools that would allow a people to interact
                    with each other outside of debt systems. We believe a responsible society using a debt free credit system would be the
                    right step towards a sustainable future.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>