<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon money"></div>
                    <div class="heading-text">
                        <h2>Alternative money</h2>
                        <h3>Interest and debt free community money</h3>
                    </div>
                </div>
                <p>
                    A vital part of any society is an accepted means of exchange. Traditionally fiat currency is used however
                    the use of this currency violates the freedom from slavery that a people enjoy. We believe in debt free,
                    interest free community based money. The proceeds of which are used for the community as apposed to being
                    use to enrich a political or social elite.
                </p>
                <p>
                    Our currency system is still in the research and development stage.
                </p>
                <p>
                    The aim is for the RGH to earn a commission off the exchanges of its members interactions and this will be the only source
                    of income used to run the country.
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>