<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon passport"></div>
                    <div class="heading-text">
                        <h2>Passport</h2>
                        <h3>Your right to "choose your government"</h3>
                    </div>
                </div>
                <p>
                    It is a perversion of terms to say that a charter gives rights. It operates by a contrary effect — that of taking rights
                    away. Rights are inherently in all the inhabitants; but charters, by annulling those rights, in the majority, leave the
                    right, by exclusion, in the hands of a few... They... consequently are instruments of injustice ... The fact, therefore,
                    must be that the individuals, themselves, each, in his own personal and sovereign right, entered into a contract with each
                    other to produce a government: and this is the only mode in which governments have a right to arise, and the only principle
                    on which they have a right to exist..<br/><br/>

                    <b>- Thomas Paine, The Rights of Man</b>
                </p>
                <p>
                    Such sovereign decision-making power of the individual in legal fact is confirmed in many national constitutions
                    as well as in all human rights declarations.	Article 15(2), Universal Declaration of Human Rights, confirms the
                    right of the individual to choose his or her government in the following words: "No one shall be arbitrarily deprived
                    of his (or her) nationality nor denied the right to change his (or her) nationality."
                </p>
                <p>
                    The changing of nationality is not only the changing of government but, more important, the choosing of government.
                    Here again, individual sovereignty is confirmed. Further, if I have the right to change my nationality, I also have
                    the reciprocal right to renounce my nationality unilaterally, the nation being merely the external vessel into which
                    I pour my portion of sovereignty as long as it serves my purpose. A refugee fleeing a repressive regime may not only
                    have the desire but for sheer survival have to renounce his or her nationality. The United States has recognized the
                    right of expatriation officially since July 27, 1868 by a special Act of Congress.
                </p>


            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>