<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-9">
                <div class="page-heading">
                    <div class="icon report"></div>
                    <div class="heading-text">
                        <h2>Reporting tools</h2>
                        <h3>Report human rights violations</h3>
                    </div>
                </div>
                <p>
                    We provide tools for our activists to report human rights violators. Be they from the state or
                    a corporation. All violators are listed with our service and the locale of the violation is marked
                    on a world map. The idea is to use this map in order to locate and remedy habitual offenders.
                </p>
                <p>
                    Violators are reported to local Human Rights Organisations and if remedy is not forth coming, we
                    approach the United Nations High Commission in order to remedy various situations.violations
                </p>
            </div>
            <?=$this->PageViewHelper()->getPublicRightMenu();?>
        </div>
    </div>
</div>