<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-heading">
                    <div class="icon identity"></div>
                    <div class="heading-text">
                        <h2>Terms and conditions</h2>
                        <h3>Terms binding members who utilise the tools of the republic</h3>
                    </div>
                </div>
                <h2>PREAMBLE</h2>
                <p>
                    By accessing or creating an account on this website, including but not limited to sub-domains of this website, you are
                    agreeing to comply with the terms, conditions and disclaimers contained in this notice. If you do not accept these
                    Terms and Conditions, do not use this website or conduct any activities through this website. Unless otherwise stated,
                    this website is not associated or endorsed by any third party organization.
                </p>
                <h2>ENROLMENT AGREEMENT</h2>
                <p>
                    The following sets forth the terms, conditions and disclaimers governing the arrangement between you,
                    the Members (hereinafter the "Member," individually) and The Republic of Good Hope (hereinafter "RGH," individually)
                    and hereinafter jointly referred to as the “Parties.”
                </p>
                <h2>ELIGIBILITY</h2>
                <p>
                    By using this website you confirm that you are at least 18 years old and/or legally
                    competent to enter into and to contractually abide by the terms, conditions, representations and warranties set
                    forth in this Agreement.
                </p>
                <h2>MEMBERSHIP</h2>
                <p>
                    Members
                </p>
            </div>
        </div>
    </div>
</div>