<div class="page-container">
    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <div class="col-sm-12">
                        <div>
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12 personal-info">
                                        <?php $this->FlashMessengerHelper(); ?>
                                        <h3>Welcome</h3>
                                        <form class="form-horizontal" role="form">
                                            <p>
                                                Before you can become a member of the Republic of Good Hope, you must download the attached document, sign it and up-load
                                                back to the system.
                                            </p>
                                            <p>
                                                The contract outlines your agreement to behave in a manner that is fitting to the societies standards. If you do not agree to the
                                                standards, then do not sign the document.
                                            </p>
                                            <a class="btn btn-warning" href="<?=$this->url('contract-pdf', ['variable' => 'download']);?>"><i class="glyphicon glyphicon-lock"></i>DOWNLOAD & READ CONTRACT</a>
                                            <a class="btn btn-success" href="<?=$this->url('contract-pdf', ['variable' => 'upload']);?>"><i class="glyphicon glyphicon-lock"></i>UPLOAD CONTRACT</a>
                                            <p>
                                                Once your contract has been uploaded a volunteer will check the document and approve your account.
                                            </p>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>