<?php
$form = $this->form;
$form->setAttribute('class', 'form-horizontal form-without-legend');
$form->prepare();
$csrf = $form->get('csrfcheck');
$user = $form->get('username');
$password = $form->get('password');
$sub  = $form->get('submit');
$form->get('username')->setAttribute('class','form-control placeholder-no-fix');
$form->get('password')->setAttribute('class','form-control placeholder-no-fix');
$form->get('submit')->setAttribute('class','btn btn-primary');
?>
<div class="page-container">
    <div class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <?php $this->FlashMessengerHelper(); ?>
                    <div class="col-sm-9">
                        <div class="page-heading">
                            <div class="icon passport"></div>
                            <div class="heading-text">
                                <h2>Login</h2>
                                <h3>Login to your account</h3>
                            </div>
                        </div>
                        <div>
                            <?=$this->form()->openTag($form);?>
                            <?=$this->formElement($csrf);?>
                            <?=$this->formElementErrors($csrf);?>
                            <div class="form-body">
                                <div class="form-group">
                                    <label class="col-lg-3 control-label"><?= $this->formLabel($user);?> <span class="require">*</span></label>
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
                                        <?= $this->formElement($user);?>
                                    </div>
                                </div>
                                <?php if (!empty($this->formElementErrors($user))) echo '<div class="alert alert-danger">That email exists in the database.</div>';?>
                                <div class="form-group">
                                    <label class="col-lg-3 control-label"><?= $this->formLabel($password); ?> <span class="require">*</span></label>
                                    <div class="input-group">
                                        <?=$this->formElement($password);?>
                                        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                                    </div>
                                    <label class="col-lg-3 control-label"></label>
                                    <div class="help-block">
                                        <?php echo $password->getOption('instructions');?>
                                    </div>
                                </div>
                                <?php if (!empty($this->formElementErrors($password))) echo '<div class="alert alert-danger">'.$this->formElementErrors($password).'</div>';?>
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="control-label col-md-3"></label>
                                        <div class="col-md-8">
                                            <div class="input-group" style="text-align:left">
                                                <?=$this->formElement($sub);?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?=$this->form()->closeTag();?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>