<?php
$this->layout('no_banner/layout');
$this->banner=false;
?>
<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <div>
                    <h1>Almost done...</h1>
                    <div class="content-page">
                        <p>
                            Please confirm your email address.<br/><br/>

                            We have sent an email to: <?=$this->email;?>, please follow the instructions in the email.<br/><br/>

                            If you have not received your confirmation email please contact: <b>info@republicofgoodhope.org</b>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
