<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-sm-9">
                <div>
                    <h1>Almost done...</h1>
                    <div class="content-page">
                        <p>
                            Please confirm your email address.
                        </p>
                        <p>
                            An email has been sent to: <?=$this->email;?>, please follow the instructions in the email.
                        </p>
                        <p>
                            If you have not received the email please contact our <u>volunteer</u> support
                            team via the: <b><a href="http://support.republicofgoodhope.org/index.php" title="Support">Support Desk</a></b>
                        </p>
                        <p>
                            <b>IMPORTANT:</b>
                        </p>
                        <ol>
                            <li>All communication from the society is offered <u>without prejudice</u></li>
                            <li>Volunteer support teams are not qualified to offer any form of <u>legal advice</u>.</li>
                            <li>You are <u>responsible</u> for all tools and services you freely choose to use as created by members of the society.</li>
                            <li>Members are <u>not entitled</u> to complain about services, they are <u>obliged</u> to take proactive measures in order to improve services or have services removed if found
                                to be harmful.</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
