<table border="0" cellpadding="5px">
    <tr>
        <td width="25%">
            <img src="/assets/global/images/bird_logo.png" width="100"><br/>
        </td>
        <td width="75%" style="vertical-align: top;">
            <h3 align="center">NOTICE: PRIVATE AUTOMOBILE VERIFICATION</h3>
            <small>This verification is offered as a means to show good faith and transparency
                when verifying the private property of RGH members.

                This verification is offered without prejudice and may not be used for entrance into any
                foreign jurisdiction or be the basis for any claim against anyone for any reason.
            </small>
        </td>
    </tr>
</table>
<table border="1" cellpadding="5px">
    <tr>
        <td><small><b>DATE: <?=date('Y-m-d');?></b><br/>
                VERIFICATION CODE: <?=$this->verificationCode;?><br/>
                RECORD NUMBER: <?=$this->recordNumber;?><br/>
                SIGNATURE: <?=md5(date('Y-m-d').$this->verificationCode.$this->recordNumber);?>
            </small>
        </td>
        <td>
            <small>
                NOTE: Kindly contact the Records committee should you wish to verify this documents signature: https://support.republicofgoodhope.org
            </small>
        </td>
    </tr>
</table>
<h3>PRIVATE AUTOMOBILE / CONVEYANCE:</h3>
<table border="0" cellpadding="5px">
    <tr>
        <td>MAKE:</td>
        <td>KIA, K2700, White</td>
    </tr>
    <tr>
        <td>TARE (unladen weight) (Kg):</td>
        <td>1530</td>
    </tr>
    <tr>
        <td>GAM (Gross Automobile Mass) (Kg):</td>
        <td>3150</td>
    </tr>
    <tr>
        <td>ENGINE CAPACITY (cc):</td>
        <td>2665</td>
    </tr>
    <tr>
        <td>AIN NUMBER (Automobile Identification Number):</td>
        <td>KNCSGX71LD7669143</td>
    </tr>
    <tr>
        <td>USAGE:</td>
        <td>PRIVATE USE ONLY, <u>STRICTLY NOT FOR PASSENGERS</u></td>
    </tr>
    <tr>
        <td>ENGINE NUMBER</td>
        <td>J2619054</td>
    </tr>
    <tr>
        <td>RECORD NUMBER</td>
        <td>RG74788H</td>
    </tr>
</table>
<h3>OWNER:</h3>
<table border="1" cellpadding="5px">
    <tr>
        <td width="25%">
            <img src="/assets/global/images/AZ196324052013440-LWRASZQQRBP.jpg" width="100px">
        </td>
        <td width="75%">
            <table border="0">
                <tr>
                    <td colspan="2"><b>PRIVATE DETAILS</b></td>
                </tr>
                <tr>
                    <td>NAME:</td>
                    <td>FM PAUL DE LUCCHI</td>
                </tr>
                <tr>
                    <td>RECORD NUMBER:</td>
                    <td>AZ196324052013440</td>
                </tr>
                <tr>
                    <td>LICENSE TYPE:</td>
                    <td>* INTERNATIONAL LICENCA VIAJAR</td>
                </tr>
                <tr>
                    <td>ALSO CONSIDERED</td>
                    <td>** An International Driving Permit</td>
                </tr>
                <tr>
                    <td>LICENSE STATUS:</td>
                    <td>CURRENT</td>
                </tr>
                <tr>
                    <td>JURISDICTION:</td>
                    <td>PRIVATE</td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="2"><b>PHYSICAL ADDRESS</b></td>
                </tr>
                <tr>
                    <td colspan="2">15 Roger Street,<br/>
                        Tygervalley, [7531, Cape Town]<br/>
                        Geography: Southern Africa<br/>
                    </td>
                </tr>
                <tr>
                    <td>GPS CO-ORDINATES:</td>
                    <td>-33.8713077, 18.6405903</td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><small>* <em>Does not allow the carrying of passengers.</em></small><br/>
                            <small>** <em>The member has provided proof of competency in order to operate an automobile and therefore the Licensia Viajar
                                    enjoys the status of "International Driving Permit".</em></small>
                        </p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>


