<p><?=$this->content;?></p>
<p>Republic of Good hope</p>
<p>IMPORTANT:</p>
<ol>
    <li>All communication from the society is offered without prejudice.</li>
    <li>Volunteer support teams are not qualified to offer any form of legal advice.</li>
    <li>You are responsible for all tools and services you freely choose to use as created by members of the society.</li>
    <li>Members are not entitled to complain about services, they are obliged to take proactive measures in order to improve services or have services removed if found to be harmful.</li>
    <li>If you wish to volunteer, kindly contact support. Remember, if no one volunteers, there can be no support.</li>
</ol>