<?=$this->content;?>

Republic of Good hope

IMPORTANT:
1. All communication from the RGH is offered without prejudice.
2. Volunteer support teams are not qualified to offer legal advice.
3. You are responsible for all RGH related tools and services you freely choose to use. If you feel uncomfortable using them, do not use them.
4. Members are obliged to take proactive measures in order to improve society services.
5. If you wish to volunteer, kindly contact support: https://support.republicofgoodhope.org
