<p><?=$this->content;?></p>
<p>Republic of Good hope</p>
<p>IMPORTANT:</p>
<ol>
    <li>All communication from the RGH is offered without prejudice.</li>
    <li>Volunteer support teams are not qualified to offer legal advice.</li>
    <li>You are responsible for all RGH related tools and services you freely choose to use. If you feel uncomfortable using them, do not use them.</li>
    <li>Members are obliged to take proactive measures in order to improve society services.</li>
    <li>If you wish to volunteer, kindly contact support: https://support.republicofgoodhope.org</li>
</ol>