<?=$this->content;?>

Republic of Good hope

IMPORTANT:
1. All communication from the society is offered without prejudice.
2. Volunteer support teams are not qualified to offer any form of legal advice.
3. You are responsible for all tools and services you freely choose to use as created by members of the society.
4. Members are not entitled to complain about services, they are obliged to take proactive measures in order to improve services or have services removed if found to be harmful.
5. If you wish to volunteer, kindly contact support. Remember, if no one volunteers, there can be no support. society was created as a result of a declaration of independence and as a vehicle through which a people may record and administer their private affairs without using debt currency. It has a sole responsibility to administer the private affairs of its members. The administration is managed by volunteers who are limited by its constitution.