<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/application.config.old
 */
return [
    'modules' => [
        'DoctrineModule',
        'DoctrineORMModule',
        'Application',
        'User',
        'Education',
    ],
    'module_listener_options' => [
        'config_glob_paths' => [
            __DIR__ . '/autoload/{,*.}{global,local}.php'
        ],
        'module_paths' => [
            __DIR__ . '/../module',
            __DIR__  .'/../vendor',
        ],
    ],
    'view_manager' => [
        'display_not_found_reason' => true,
        'display_exceptions' => true,
    ],
];
